version: '3.8'

services:
  postgres-db:
    image: postgres:15.2-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD:  root
      POSTGRES_USER:      root
      POSTGRES_DB:        base
      PGPORT:             5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: